### ISSUE TITLE
I want to deploy simple contract to the reef testnet chain. But reefRemix is not working yet.

### ISSUE THREAD

**Issue by JSTop1Coder** [JSTop1Coder/hardhat-reef-demo#1]

**Comment by Gouldian0120** [comment]
take a look at https://github.com/reef-chain/hardhat-reef-examples.

**Comment by Gouldian0120** [comment]
I just tried a newly cloned https://github.com/reef-chain/hardhat-reef-examples and created this token https://testnet.reefscan.info/contract/0x2BD7a41cA048E1b861720c6667bf83a8f8241d00 from scripts/erc20/deploy_and_verify.js

**Comment by JSTop1Coder** [comment]
Thanks for your supporting
